services:
  - type: web
    name: my-laravel-app
    env: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader

      php artisan migrate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache