name: Keep Supabase Active

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at noon UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Perform a simple SELECT query
          response=$(curl -s -w "\n%{http_code}" \
            "${SUPABASE_URL}/rest/v1/customers?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
            -H "Content-Type: application/json")

          # Extract HTTP status code
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
            
          echo "HTTP Status: $http_code"
          echo "Response: $body"

          # Check if request was successful
          if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 206 ]; then
            echo "✓ Successfully queried Supabase database"
            exit 0
          else
            echo "✗ Failed to query database"
            exit 1
          fi
